### ISSUE TITLE
Doesn't work with latest docs

### ISSUE THREAD

**Issue by hongkongkiwi** [wils0ns/tfis#1]
Doesn't seem to work with the latest docs....

e.g. `tfis digitalocean_ssh_key` produces the url: //www.terraform.io/docs/providers/digitalocean/r/ssh_key.html

But infact it should be:
https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/ssh_key

**Comment by wils0ns** [comment]
Yeah. A basic scrapping is not enough now.
I just spend some time gathering the endpoints that terraform itself uses to lookup docs:

1. Filter provider by name (id was 605):
https://registry.terraform.io/v2/providers?filter%5Bnamespace%5D=digitalocean&filter%5Bname%5D=digitalocean&filter%5Bwithout-versions%5D=true

2. Get provider version ID (latest version id: 4913):
https://registry.terraform.io/v2/providers/605?include=categories%2Cprovider-versions%2Ctop-modules

3. Check if provider exists:
https://registry.terraform.io/v2/provider-versions/4913

4. Get docs:
https://registry.terraform.io/v2/provider-versions/4913?include=provider-docs


I will refactor the module to leverage the steps above.
